/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major_project;

import javafx.application.Application;
import javafx.stage.Stage;
import major_project.model.API.Calls.FoodDataBaseAPIHTML;
import major_project.model.Engine;
import major_project.view.Window;

public class App extends Application {
    private final Engine engine = new Engine(new FoodDataBaseAPIHTML());
    private final Window window = new Window(engine);

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage){
        primaryStage.setScene(window.getScene());
        primaryStage.setTitle("FOOD");
        primaryStage.show();
        primaryStage.setHeight(480);
        primaryStage.setWidth(720);
    }
}
